version: '3.7'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      target: debug
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules